### ISSUE TITLE
Retrieving incremental ODM dataset does not work

### ISSUE THREAD

**Issue by filipcecha** [mdsol/rwslib#125]
Hello,

when making a GET request to `https://{host}/RaveWebServices/studies/{study-oid}/datasets/{regular-or-raw}[/{form-oid}][?{query-string-parameters}]` with `start` query param the response is a `This service is not implemented [RWS00140]` 

Does study have to be configured in some particular way to support incremental requests ?

**Comment by isparks** [comment]
I believe in order for incremental pulls to work the Clinical Views have to be set to "Include Inactive".

![image](https://user-images.githubusercontent.com/1135502/125635453-c8720308-f5cb-4652-856b-0db720a1d064.png)

Unless you do that, the system can't work out if records have been inactivated and when because inactivated records don't appear in the underlying clinical views.  

But the downside of setting that value is that you now get a new column in the views which indicate whether a record is active or not. This can really confuse your SAS programmers if they don't know about filtering out the inactive records so you want to be careful about when you use this.

**Comment by filipcecha** [comment]
@isparks thank you for super fast response :) ... I will check it and get back to you in case of some further questions :)
