### ISSUE TITLE
Handling ALS skip logic 

### ISSUE THREAD

**Issue by vagarwal77** [mdsol/rwslib#129]
In ALS spreadsheet -> checks has conditional skip logic. I have 2 sample example below - 
Is there a tool, API or way to load or parse these checks for application to understand these checks? Any idea or guidance would be of great help -

If A_DX_IRTDAT in Subject with record position 0 IsPresent  then... set datapoint value for X_ENROLLYN in Subject with record position 0 to YES

If X_CMYN in Prior and Concomitant Medications Prompt with record position 0 IsEqualTo YES  then... add the "Concomitant Medications" form to the current folder

**Comment by isparks** [comment]
You are looking at the description column of the Checks tab in in the ALS spreadsheet. Although you could write a parser for this description column I think you would be better looking at the CheckSteps and CheckActions tabs of the spreadsheet since these are the logical steps in Infix Format and the CheckActions to run, respectively. They are basically the equivalent of the QuickEdit you see in Rave and much easier to parse.

**Comment by glow-mdsol** [comment]
Seems like this is ok to close.
