### ISSUE TITLE
Should I cache RWSConnection objects?

### ISSUE THREAD

**Issue by terrisgit** [mdsol/rwslib#88]
Hello,

I have a multi-threaded app. Each time something is sent to RAVE, my app creates a new RWSConnection. This is probably inefficient. Are there reasons to not cache this object and reuse it?

Should I cache one RWSConnection per thread and reuse it? Or can all threads use the same instance?

Thank you!

**Comment by isparks** [comment]
RWSConnection objects are pretty lightweight, they don't hold open any connections  but they do have a last_result which stores the result of the last request they made.

https://rwslib.readthedocs.io/en/latest/getting_started.html#getting-more-information-from-last-result

I think that makes them a bad choice for multithreaded apps since one thread will clobber anothers last result. You could just consider creating an RWSConnection each time you need it. They're really just a convenience wrapper around the requests library.

**Comment by terrisgit** [comment]
Thank you!
